version: "3.7"
services:
  dbDefault:
    platform: linux/amd64
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - db-default-data:/home/postgres/pgdata/data
volumes:
  db-default-data:
    driver: local
